### ISSUE TITLE
RangeError: Maximum call stack size exceeded when building --prod --release with lazy loading

### ISSUE THREAD

**Issue by Chumillas** [mumairofficial/text-avatar#7]
I'm getting this error when using this directive with lazy loading:
`ionic cordova build android --prod --release` 

```
RangeError: Maximum call stack size exceeded
    at Set.has (native)
    at AotSummaryResolver._loadSummaryFile (C:\app\node_modules\@angular\compiler\bundles\compiler.umd.js:25734:34)
    at AotSummaryResolver.resolveSummary (C:\app\node_modules\@angular\compiler\bundles\compiler.umd.js:25702:18)
    at CompileMetadataResolver._loadSummary (C:\app\node_modules\@angular\compiler\bundles\compiler.umd.js:15123:66)
    at CompileMetadataResolver.getNgModuleSummary (C:\app\node_modules\@angular\compiler\bundles\compiler.umd.js:15356:52)
    at C:\app\node_modules\@angular\compiler\bundles\compiler.umd.js:15450:68
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\app\node_modules\@angular\compiler\bundles\compiler.umd.js:15445:49)
    at CompileMetadataResolver.getNgModuleSummary (C:\app\node_modules\@angular\compiler\bundles\compiler.umd.js:15358:52)
    at C:\app\node_modules\@angular\compiler\bundles\compiler.umd.js:15450:68
```

text-avatar.module.ts
```
import {NgModule} from '@angular/core';

@NgModule({
    declarations: [TextAvatarModule],
    exports: [TextAvatarModule],
})
export class TextAvatarModule {}

```

**Comment by mumairofficial** [comment]
hi @Chumillas, sorry I was on vocation. Hopefully you would have resolved this issue. 

Just in case can you please share ionic setup information in your project; just run `ionic info` into project root directory. I will try to reproduce this issue.

**Comment by Chumillas** [comment]
Hi @mumairofficial, I didn't fix it yet. 
My ionic info is the following:

> @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1
    cordova (Cordova CLI) : 7.1.0

> local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 and 6.3.0
    Ionic Framework    : ionic-angular 3.9.2
    Node : v9.7.1
    npm  : 5.6.0
    OS   : Windows 10

**Comment by mumairofficial** [comment]
@Chumillas I got the error actually its right in your code. The code you have provided above `text-avatar.module.ts` in **declarations** array it should be `TextAvatarDirective` instead of `TextAvatarModule`. I have provided some guides below:

#### Directive Source:
https://github.com/mumairofficial/text-avatar/blob/master/example-app/src/directives/text-avatar/text-avatar.ts

#### Usage:
https://github.com/mumairofficial/text-avatar/blob/9efbc7cecd775db80050d6c709fc6c3fbadfb69d/example-app/src/app/app.module.ts#L16

follow the [example project](https://github.com/mumairofficial/text-avatar/tree/master/example-app) for understanding.

--
Here is why you are seeing **RangeError** you have created **TextAvatarModule** and in its `declerations` and `exports` array you are giving same module (`TextAvatarModule`) which you just have created. When it start resolving it creates circular dependency which breaks on maximum call stack limits. Hope you get the problem cause!
